/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://%1$s.cloudfs.io";

    //TODO: Replace the accountId with an appropriate value
    public static String accountId = "TODO Add Value for parameter...";

    //OAuth 2.0 Access Token
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static String oAuthAccessToken = "TODO: Replace";

}
