/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AccountPlan 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5236586560983986228L;
    private String ctaText;
    private String displayName;
    private String ctaValue;
    private String id;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cta_text")
    public String getCtaText ( ) { 
        return this.ctaText;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cta_text")
    public void setCtaText (String value) { 
        this.ctaText = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("display_name")
    public String getDisplayName ( ) { 
        return this.displayName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("display_name")
    public void setDisplayName (String value) { 
        this.displayName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cta_value")
    public String getCtaValue ( ) { 
        return this.ctaValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cta_value")
    public void setCtaValue (String value) { 
        this.ctaValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
}
 