/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class AccountPlanBuilder {
    //the instance to build
    private AccountPlan accountPlan;

    /**
     * Default constructor to initialize the instance
     */
    public AccountPlanBuilder() {
        accountPlan = new AccountPlan();
    }

    public AccountPlanBuilder ctaText(String ctaText) {
        accountPlan.setCtaText(ctaText);
        return this;
    }

    public AccountPlanBuilder displayName(String displayName) {
        accountPlan.setDisplayName(displayName);
        return this;
    }

    public AccountPlanBuilder ctaValue(String ctaValue) {
        accountPlan.setCtaValue(ctaValue);
        return this;
    }

    public AccountPlanBuilder id(String id) {
        accountPlan.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountPlan build() {
        return accountPlan;
    }
}