/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class AccountStateBuilder {
    //the instance to build
    private AccountState accountState;

    /**
     * Default constructor to initialize the instance
     */
    public AccountStateBuilder() {
        accountState = new AccountState();
    }

    public AccountStateBuilder displayName(String displayName) {
        accountState.setDisplayName(displayName);
        return this;
    }

    public AccountStateBuilder id(String id) {
        accountState.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountState build() {
        return accountState;
    }
}