/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AuthenticationResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4662010068805660829L;
    private String accessToke;
    private String tokenType;
    private String error;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("access_toke")
    public String getAccessToke ( ) { 
        return this.accessToke;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("access_toke")
    public void setAccessToke (String value) { 
        this.accessToke = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("token_type")
    public String getTokenType ( ) { 
        return this.tokenType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("token_type")
    public void setTokenType (String value) { 
        this.tokenType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("error")
    public String getError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("error")
    public void setError (String value) { 
        this.error = value;
    }
 
}
 