/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class AuthenticationResponseBuilder {
    //the instance to build
    private AuthenticationResponse authenticationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AuthenticationResponseBuilder() {
        authenticationResponse = new AuthenticationResponse();
    }

    public AuthenticationResponseBuilder accessToke(String accessToke) {
        authenticationResponse.setAccessToke(accessToke);
        return this;
    }

    public AuthenticationResponseBuilder tokenType(String tokenType) {
        authenticationResponse.setTokenType(tokenType);
        return this;
    }

    public AuthenticationResponseBuilder error(String error) {
        authenticationResponse.setError(error);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AuthenticationResponse build() {
        return authenticationResponse;
    }
}