/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class BrowseShareResultBuilder {
    //the instance to build
    private BrowseShareResult browseShareResult;

    /**
     * Default constructor to initialize the instance
     */
    public BrowseShareResultBuilder() {
        browseShareResult = new BrowseShareResult();
    }

    public BrowseShareResultBuilder share(ResultShare share) {
        browseShareResult.setShare(share);
        return this;
    }

    public BrowseShareResultBuilder meta(Meta meta) {
        browseShareResult.setMeta(meta);
        return this;
    }

    public BrowseShareResultBuilder items(List<Meta> items) {
        browseShareResult.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BrowseShareResult build() {
        return browseShareResult;
    }
}