/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BrowseTrashResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4619297722565095515L;
    private String error;
    private ResultBrowseTrash results;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("error")
    public String getError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("error")
    public void setError (String value) { 
        this.error = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("results")
    public ResultBrowseTrash getResults ( ) { 
        return this.results;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("results")
    public void setResults (ResultBrowseTrash value) { 
        this.results = value;
    }
 
}
 