/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class BrowseTrashResponseBuilder {
    //the instance to build
    private BrowseTrashResponse browseTrashResponse;

    /**
     * Default constructor to initialize the instance
     */
    public BrowseTrashResponseBuilder() {
        browseTrashResponse = new BrowseTrashResponse();
    }

    public BrowseTrashResponseBuilder error(String error) {
        browseTrashResponse.setError(error);
        return this;
    }

    public BrowseTrashResponseBuilder results(ResultBrowseTrash results) {
        browseTrashResponse.setResults(results);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BrowseTrashResponse build() {
        return browseTrashResponse;
    }
}