/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class BrowseShareResult 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4847961306779103565L;
    private ResultShare share;
    private Meta meta;
    private List<Meta> items;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("share")
    public ResultShare getShare ( ) { 
        return this.share;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("share")
    public void setShare (ResultShare value) { 
        this.share = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("meta")
    public Meta getMeta ( ) { 
        return this.meta;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("meta")
    public void setMeta (Meta value) { 
        this.meta = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("items")
    public List<Meta> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("items")
    public void setItems (List<Meta> value) { 
        this.items = value;
    }
 
}
 