/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class CopyAndMoveFileResponseBuilder {
    //the instance to build
    private CopyAndMoveFileResponse copyAndMoveFileResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CopyAndMoveFileResponseBuilder() {
        copyAndMoveFileResponse = new CopyAndMoveFileResponse();
    }

    public CopyAndMoveFileResponseBuilder error(String error) {
        copyAndMoveFileResponse.setError(error);
        return this;
    }

    public CopyAndMoveFileResponseBuilder result(ResultCopyFile result) {
        copyAndMoveFileResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CopyAndMoveFileResponse build() {
        return copyAndMoveFileResponse;
    }
}