/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class CreateAndAlterShareResponseBuilder {
    //the instance to build
    private CreateAndAlterShareResponse createAndAlterShareResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CreateAndAlterShareResponseBuilder() {
        createAndAlterShareResponse = new CreateAndAlterShareResponse();
    }

    public CreateAndAlterShareResponseBuilder error(String error) {
        createAndAlterShareResponse.setError(error);
        return this;
    }

    public CreateAndAlterShareResponseBuilder result(ResultShare result) {
        createAndAlterShareResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateAndAlterShareResponse build() {
        return createAndAlterShareResponse;
    }
}