/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class CreateFolderResponseBuilder {
    //the instance to build
    private CreateFolderResponse createFolderResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CreateFolderResponseBuilder() {
        createFolderResponse = new CreateFolderResponse();
    }

    public CreateFolderResponseBuilder error(String error) {
        createFolderResponse.setError(error);
        return this;
    }

    public CreateFolderResponseBuilder result(ResultFolder result) {
        createFolderResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateFolderResponse build() {
        return createFolderResponse;
    }
}