/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import org.joda.time.DateTime;

public class DataBuilder {
    //the instance to build
    private Data data;

    /**
     * Default constructor to initialize the instance
     */
    public DataBuilder() {
        data = new Data();
    }

    public DataBuilder shareKey(String shareKey) {
        data.setShareKey(shareKey);
        return this;
    }

    public DataBuilder exists(String exists) {
        data.setExists(exists);
        return this;
    }

    public DataBuilder path(List<String> path) {
        data.setPath(path);
        return this;
    }

    public DataBuilder shareUrl(String shareUrl) {
        data.setShareUrl(shareUrl);
        return this;
    }

    public DataBuilder id(String id) {
        data.setId(id);
        return this;
    }

    public DataBuilder applicationData(String applicationData) {
        data.setApplicationData(applicationData);
        return this;
    }

    public DataBuilder name(String name) {
        data.setName(name);
        return this;
    }

    public DataBuilder dateCreated(DateTime dateCreated) {
        data.setDateCreated(dateCreated);
        return this;
    }

    public DataBuilder to(String to) {
        data.setTo(to);
        return this;
    }

    public DataBuilder parentId(String parentId) {
        data.setParentId(parentId);
        return this;
    }

    public DataBuilder dateMetaLastModified(DateTime dateMetaLastModified) {
        data.setDateMetaLastModified(dateMetaLastModified);
        return this;
    }

    public DataBuilder dateContentLastModified(DateTime dateContentLastModified) {
        data.setDateContentLastModified(dateContentLastModified);
        return this;
    }

    public DataBuilder size(int size) {
        data.setSize(size);
        return this;
    }

    public DataBuilder mime(String mime) {
        data.setMime(mime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data build() {
        return data;
    }
}