/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.cloudfs.DateTimeHelper;
import org.joda.time.DateTime;

public class Data 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4832753487646333556L;
    private String shareKey;
    private String exists;
    private List<String> path;
    private String shareUrl;
    private String id;
    private String applicationData;
    private String name;
    private DateTime dateCreated;
    private String to;
    private String parentId;
    private DateTime dateMetaLastModified;
    private DateTime dateContentLastModified;
    private int size;
    private String mime;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("share_key")
    public String getShareKey ( ) { 
        return this.shareKey;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("share_key")
    public void setShareKey (String value) { 
        this.shareKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exists")
    public String getExists ( ) { 
        return this.exists;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exists")
    public void setExists (String value) { 
        this.exists = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("path")
    public List<String> getPath ( ) { 
        return this.path;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("path")
    public void setPath (List<String> value) { 
        this.path = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("share_url")
    public String getShareUrl ( ) { 
        return this.shareUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("share_url")
    public void setShareUrl (String value) { 
        this.shareUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("application_data")
    public String getApplicationData ( ) { 
        return this.applicationData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("application_data")
    public void setApplicationData (String value) { 
        this.applicationData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_created")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateCreated ( ) { 
        return this.dateCreated;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_created")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateCreated (DateTime value) { 
        this.dateCreated = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("to")
    public String getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("to")
    public void setTo (String value) { 
        this.to = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parent_id")
    public String getParentId ( ) { 
        return this.parentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parent_id")
    public void setParentId (String value) { 
        this.parentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_meta_last_modified")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateMetaLastModified ( ) { 
        return this.dateMetaLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_meta_last_modified")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateMetaLastModified (DateTime value) { 
        this.dateMetaLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_content_last_modified")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateContentLastModified ( ) { 
        return this.dateContentLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_content_last_modified")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateContentLastModified (DateTime value) { 
        this.dateContentLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public int getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (int value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mime")
    public String getMime ( ) { 
        return this.mime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mime")
    public void setMime (String value) { 
        this.mime = value;
    }
 
}
 