/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class DeleteFileResponseBuilder {
    //the instance to build
    private DeleteFileResponse deleteFileResponse;

    /**
     * Default constructor to initialize the instance
     */
    public DeleteFileResponseBuilder() {
        deleteFileResponse = new DeleteFileResponse();
    }

    public DeleteFileResponseBuilder error(String error) {
        deleteFileResponse.setError(error);
        return this;
    }

    public DeleteFileResponseBuilder result(ResultDeleteFile result) {
        deleteFileResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeleteFileResponse build() {
        return deleteFileResponse;
    }
}