/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ExistsEnum {
    FAIL, //TODO: Write general description for this element
    OVERWRITE, //TODO: Write general description for this element
    RENAME, //TODO: Write general description for this element
    REUSE; //TODO: Write general description for this element

    private static TreeMap<String, ExistsEnum> valueMap = new TreeMap<String, ExistsEnum>();
    private String value;

    static {
        FAIL.value = "fail";
        OVERWRITE.value = "overwrite";
        RENAME.value = "rename";
        REUSE.value = "reuse";

        valueMap.put("fail", FAIL);
        valueMap.put("overwrite", OVERWRITE);
        valueMap.put("rename", RENAME);
        valueMap.put("reuse", REUSE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ExistsEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ExistsEnum values to list of string values
     * @param toConvert The list of ExistsEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ExistsEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ExistsEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 