/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class GetProfileResponseBuilder {
    //the instance to build
    private GetProfileResponse getProfileResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetProfileResponseBuilder() {
        getProfileResponse = new GetProfileResponse();
    }

    public GetProfileResponseBuilder error(String error) {
        getProfileResponse.setError(error);
        return this;
    }

    public GetProfileResponseBuilder result(Result result) {
        getProfileResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetProfileResponse build() {
        return getProfileResponse;
    }
}