/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Holds 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5499427846964916236L;
    private boolean deleted;
    private boolean otl;
    private boolean suspended;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deleted")
    public boolean getDeleted ( ) { 
        return this.deleted;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deleted")
    public void setDeleted (boolean value) { 
        this.deleted = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("otl")
    public boolean getOtl ( ) { 
        return this.otl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("otl")
    public void setOtl (boolean value) { 
        this.otl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("suspended")
    public boolean getSuspended ( ) { 
        return this.suspended;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("suspended")
    public void setSuspended (boolean value) { 
        this.suspended = value;
    }
 
}
 