/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class HoldsBuilder {
    //the instance to build
    private Holds holds;

    /**
     * Default constructor to initialize the instance
     */
    public HoldsBuilder() {
        holds = new Holds();
    }

    public HoldsBuilder deleted(boolean deleted) {
        holds.setDeleted(deleted);
        return this;
    }

    public HoldsBuilder otl(boolean otl) {
        holds.setOtl(otl);
        return this;
    }

    public HoldsBuilder suspended(boolean suspended) {
        holds.setSuspended(suspended);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Holds build() {
        return holds;
    }
}