/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ListSingleFileVersionResponseBuilder {
    //the instance to build
    private ListSingleFileVersionResponse listSingleFileVersionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListSingleFileVersionResponseBuilder() {
        listSingleFileVersionResponse = new ListSingleFileVersionResponse();
    }

    public ListSingleFileVersionResponseBuilder error(String error) {
        listSingleFileVersionResponse.setError(error);
        return this;
    }

    public ListSingleFileVersionResponseBuilder result(Meta result) {
        listSingleFileVersionResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListSingleFileVersionResponse build() {
        return listSingleFileVersionResponse;
    }
}