/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ListHistoryResponseBuilder {
    //the instance to build
    private ListHistoryResponse listHistoryResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListHistoryResponseBuilder() {
        listHistoryResponse = new ListHistoryResponse();
    }

    public ListHistoryResponseBuilder error(String error) {
        listHistoryResponse.setError(error);
        return this;
    }

    public ListHistoryResponseBuilder result(List<ResultHistory> result) {
        listHistoryResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListHistoryResponse build() {
        return listHistoryResponse;
    }
}