/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ListFileVersionsResponseBuilder {
    //the instance to build
    private ListFileVersionsResponse listFileVersionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListFileVersionsResponseBuilder() {
        listFileVersionsResponse = new ListFileVersionsResponse();
    }

    public ListFileVersionsResponseBuilder error(String error) {
        listFileVersionsResponse.setError(error);
        return this;
    }

    public ListFileVersionsResponseBuilder result(List<Meta> result) {
        listFileVersionsResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListFileVersionsResponse build() {
        return listFileVersionsResponse;
    }
}