/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ListShareResponseBuilder {
    //the instance to build
    private ListShareResponse listShareResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListShareResponseBuilder() {
        listShareResponse = new ListShareResponse();
    }

    public ListShareResponseBuilder error(String error) {
        listShareResponse.setError(error);
        return this;
    }

    public ListShareResponseBuilder result(List<ResultShare> result) {
        listShareResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListShareResponse build() {
        return listShareResponse;
    }
}