/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ListFolderResponseBuilder {
    //the instance to build
    private ListFolderResponse listFolderResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListFolderResponseBuilder() {
        listFolderResponse = new ListFolderResponse();
    }

    public ListFolderResponseBuilder error(String error) {
        listFolderResponse.setError(error);
        return this;
    }

    public ListFolderResponseBuilder result(ResultListFolder result) {
        listFolderResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListFolderResponse build() {
        return listFolderResponse;
    }
}