/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import org.joda.time.DateTime;

public class MetaBuilder {
    //the instance to build
    private Meta meta;

    /**
     * Default constructor to initialize the instance
     */
    public MetaBuilder() {
        meta = new Meta();
    }

    public MetaBuilder id(String id) {
        meta.setId(id);
        return this;
    }

    public MetaBuilder parentId(String parentId) {
        meta.setParentId(parentId);
        return this;
    }

    public MetaBuilder type(String type) {
        meta.setType(type);
        return this;
    }

    public MetaBuilder name(String name) {
        meta.setName(name);
        return this;
    }

    public MetaBuilder extension(String extension) {
        meta.setExtension(extension);
        return this;
    }

    public MetaBuilder dateCreated(DateTime dateCreated) {
        meta.setDateCreated(dateCreated);
        return this;
    }

    public MetaBuilder dateMetaLastModified(DateTime dateMetaLastModified) {
        meta.setDateMetaLastModified(dateMetaLastModified);
        return this;
    }

    public MetaBuilder dateContentLastModified(DateTime dateContentLastModified) {
        meta.setDateContentLastModified(dateContentLastModified);
        return this;
    }

    public MetaBuilder size(int size) {
        meta.setSize(size);
        return this;
    }

    public MetaBuilder mime(String mime) {
        meta.setMime(mime);
        return this;
    }

    public MetaBuilder version(int version) {
        meta.setVersion(version);
        return this;
    }

    public MetaBuilder applicationData(LinkedHashMap<String, Object> applicationData) {
        meta.setApplicationData(applicationData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Meta build() {
        return meta;
    }
}