/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.cloudfs.DateTimeHelper;
import org.joda.time.DateTime;

public class Meta 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4622553804192445295L;
    private String id;
    private String parentId;
    private String type;
    private String name;
    private String extension;
    private DateTime dateCreated;
    private DateTime dateMetaLastModified;
    private DateTime dateContentLastModified;
    private int size;
    private String mime;
    private int version;
    private LinkedHashMap<String, Object> applicationData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parent_id")
    public String getParentId ( ) { 
        return this.parentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parent_id")
    public void setParentId (String value) { 
        this.parentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extension")
    public String getExtension ( ) { 
        return this.extension;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extension")
    public void setExtension (String value) { 
        this.extension = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_created")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateCreated ( ) { 
        return this.dateCreated;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_created")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateCreated (DateTime value) { 
        this.dateCreated = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_meta_last_modified")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateMetaLastModified ( ) { 
        return this.dateMetaLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_meta_last_modified")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateMetaLastModified (DateTime value) { 
        this.dateMetaLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_content_last_modified")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateContentLastModified ( ) { 
        return this.dateContentLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_content_last_modified")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateContentLastModified (DateTime value) { 
        this.dateContentLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public int getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (int value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mime")
    public String getMime ( ) { 
        return this.mime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mime")
    public void setMime (String value) { 
        this.mime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("version")
    public int getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("version")
    public void setVersion (int value) { 
        this.version = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("application_data")
    public LinkedHashMap<String, Object> getApplicationData ( ) { 
        return this.applicationData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("application_data")
    public void setApplicationData (LinkedHashMap<String, Object> value) { 
        this.applicationData = value;
    }
 
}
 