/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ReceiveAndUnlockShareResponseBuilder {
    //the instance to build
    private ReceiveAndUnlockShareResponse receiveAndUnlockShareResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ReceiveAndUnlockShareResponseBuilder() {
        receiveAndUnlockShareResponse = new ReceiveAndUnlockShareResponse();
    }

    public ReceiveAndUnlockShareResponseBuilder error(String error) {
        receiveAndUnlockShareResponse.setError(error);
        return this;
    }

    public ReceiveAndUnlockShareResponseBuilder result(ResultUnlockAndReceiveShare result) {
        receiveAndUnlockShareResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReceiveAndUnlockShareResponse build() {
        return receiveAndUnlockShareResponse;
    }
}