/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultBrowseTrashBuilder {
    //the instance to build
    private ResultBrowseTrash resultBrowseTrash;

    /**
     * Default constructor to initialize the instance
     */
    public ResultBrowseTrashBuilder() {
        resultBrowseTrash = new ResultBrowseTrash();
    }

    public ResultBrowseTrashBuilder meta(Meta meta) {
        resultBrowseTrash.setMeta(meta);
        return this;
    }

    public ResultBrowseTrashBuilder items(List<Meta> items) {
        resultBrowseTrash.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultBrowseTrash build() {
        return resultBrowseTrash;
    }
}