/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.cloudfs.DateTimeHelper;
import org.joda.time.DateTime;

public class ResultShare 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5413644386787602779L;
    private String shareKey;
    private String url;
    private String shortUrl;
    private int size;
    private DateTime dateCreated;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("share_key")
    public String getShareKey ( ) { 
        return this.shareKey;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("share_key")
    public void setShareKey (String value) { 
        this.shareKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("short_url")
    public String getShortUrl ( ) { 
        return this.shortUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("short_url")
    public void setShortUrl (String value) { 
        this.shortUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public int getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (int value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_created")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDateCreated ( ) { 
        return this.dateCreated;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_created")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateCreated (DateTime value) { 
        this.dateCreated = value;
    }
 
}
 