/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultDeleteFileBuilder {
    //the instance to build
    private ResultDeleteFile resultDeleteFile;

    /**
     * Default constructor to initialize the instance
     */
    public ResultDeleteFileBuilder() {
        resultDeleteFile = new ResultDeleteFile();
    }

    public ResultDeleteFileBuilder success(boolean success) {
        resultDeleteFile.setSuccess(success);
        return this;
    }

    public ResultDeleteFileBuilder version(int version) {
        resultDeleteFile.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultDeleteFile build() {
        return resultDeleteFile;
    }
}