/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultUnlockAndReceiveShareBuilder {
    //the instance to build
    private ResultUnlockAndReceiveShare resultUnlockAndReceiveShare;

    /**
     * Default constructor to initialize the instance
     */
    public ResultUnlockAndReceiveShareBuilder() {
        resultUnlockAndReceiveShare = new ResultUnlockAndReceiveShare();
    }

    public ResultUnlockAndReceiveShareBuilder success(boolean success) {
        resultUnlockAndReceiveShare.setSuccess(success);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultUnlockAndReceiveShare build() {
        return resultUnlockAndReceiveShare;
    }
}