/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ResultUpload 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5116577150812774131L;
    private String id;
    private String parentId;
    private String type;
    private String name;
    private String extension;
    private double dateCreated;
    private double dateMetaLastModified;
    private double dateContentLastModified;
    private String mime;
    private double size;
    private String version;
    private List<String> applicationData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parent_id")
    public String getParentId ( ) { 
        return this.parentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parent_id")
    public void setParentId (String value) { 
        this.parentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extension")
    public String getExtension ( ) { 
        return this.extension;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extension")
    public void setExtension (String value) { 
        this.extension = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_created")
    public double getDateCreated ( ) { 
        return this.dateCreated;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_created")
    public void setDateCreated (double value) { 
        this.dateCreated = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_meta_last_modified")
    public double getDateMetaLastModified ( ) { 
        return this.dateMetaLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_meta_last_modified")
    public void setDateMetaLastModified (double value) { 
        this.dateMetaLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("date_content_last_modified")
    public double getDateContentLastModified ( ) { 
        return this.dateContentLastModified;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("date_content_last_modified")
    public void setDateContentLastModified (double value) { 
        this.dateContentLastModified = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mime")
    public String getMime ( ) { 
        return this.mime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mime")
    public void setMime (String value) { 
        this.mime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public double getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (double value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("version")
    public String getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("version")
    public void setVersion (String value) { 
        this.version = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("application_data")
    public List<String> getApplicationData ( ) { 
        return this.applicationData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("application_data")
    public void setApplicationData (List<String> value) { 
        this.applicationData = value;
    }
 
}
 