/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultFolderBuilder {
    //the instance to build
    private ResultFolder resultFolder;

    /**
     * Default constructor to initialize the instance
     */
    public ResultFolderBuilder() {
        resultFolder = new ResultFolder();
    }

    public ResultFolderBuilder items(List<Meta> items) {
        resultFolder.setItems(items);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultFolder build() {
        return resultFolder;
    }
}