/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultHistoryBuilder {
    //the instance to build
    private ResultHistory resultHistory;

    /**
     * Default constructor to initialize the instance
     */
    public ResultHistoryBuilder() {
        resultHistory = new ResultHistory();
    }

    public ResultHistoryBuilder version(String version) {
        resultHistory.setVersion(version);
        return this;
    }

    public ResultHistoryBuilder action(String action) {
        resultHistory.setAction(action);
        return this;
    }

    public ResultHistoryBuilder path(String path) {
        resultHistory.setPath(path);
        return this;
    }

    public ResultHistoryBuilder type(String type) {
        resultHistory.setType(type);
        return this;
    }

    public ResultHistoryBuilder data(Data data) {
        resultHistory.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultHistory build() {
        return resultHistory;
    }
}