/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultUploadBuilder {
    //the instance to build
    private ResultUpload resultUpload;

    /**
     * Default constructor to initialize the instance
     */
    public ResultUploadBuilder() {
        resultUpload = new ResultUpload();
    }

    public ResultUploadBuilder id(String id) {
        resultUpload.setId(id);
        return this;
    }

    public ResultUploadBuilder parentId(String parentId) {
        resultUpload.setParentId(parentId);
        return this;
    }

    public ResultUploadBuilder type(String type) {
        resultUpload.setType(type);
        return this;
    }

    public ResultUploadBuilder name(String name) {
        resultUpload.setName(name);
        return this;
    }

    public ResultUploadBuilder extension(String extension) {
        resultUpload.setExtension(extension);
        return this;
    }

    public ResultUploadBuilder dateCreated(double dateCreated) {
        resultUpload.setDateCreated(dateCreated);
        return this;
    }

    public ResultUploadBuilder dateMetaLastModified(double dateMetaLastModified) {
        resultUpload.setDateMetaLastModified(dateMetaLastModified);
        return this;
    }

    public ResultUploadBuilder dateContentLastModified(double dateContentLastModified) {
        resultUpload.setDateContentLastModified(dateContentLastModified);
        return this;
    }

    public ResultUploadBuilder mime(String mime) {
        resultUpload.setMime(mime);
        return this;
    }

    public ResultUploadBuilder size(double size) {
        resultUpload.setSize(size);
        return this;
    }

    public ResultUploadBuilder version(String version) {
        resultUpload.setVersion(version);
        return this;
    }

    public ResultUploadBuilder applicationData(List<String> applicationData) {
        resultUpload.setApplicationData(applicationData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultUpload build() {
        return resultUpload;
    }
}