/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultBuilder {
    //the instance to build
    private Result result;

    /**
     * Default constructor to initialize the instance
     */
    public ResultBuilder() {
        result = new Result();
    }

    public ResultBuilder username(String username) {
        result.setUsername(username);
        return this;
    }

    public ResultBuilder createdAt(double createdAt) {
        result.setCreatedAt(createdAt);
        return this;
    }

    public ResultBuilder firstName(String firstName) {
        result.setFirstName(firstName);
        return this;
    }

    public ResultBuilder lastName(String lastName) {
        result.setLastName(lastName);
        return this;
    }

    public ResultBuilder accountId(String accountId) {
        result.setAccountId(accountId);
        return this;
    }

    public ResultBuilder locale(String locale) {
        result.setLocale(locale);
        return this;
    }

    public ResultBuilder accountState(AccountState accountState) {
        result.setAccountState(accountState);
        return this;
    }

    public ResultBuilder storage(Storage storage) {
        result.setStorage(storage);
        return this;
    }

    public ResultBuilder accountPlan(AccountPlan accountPlan) {
        result.setAccountPlan(accountPlan);
        return this;
    }

    public ResultBuilder email(String email) {
        result.setEmail(email);
        return this;
    }

    public ResultBuilder session(Session session) {
        result.setSession(session);
        return this;
    }

    public ResultBuilder lastLogin(String lastLogin) {
        result.setLastLogin(lastLogin);
        return this;
    }

    public ResultBuilder id(String id) {
        result.setId(id);
        return this;
    }

    public ResultBuilder holds(Holds holds) {
        result.setHolds(holds);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Result build() {
        return result;
    }
}