/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ResultFolder 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5055374127191482832L;
    private List<Meta> items;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("items")
    public List<Meta> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("items")
    public void setItems (List<Meta> value) { 
        this.items = value;
    }
 
}
 