/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ResultListFolder 
        extends ResultFolder {
    private static final long serialVersionUID = 4919433958231253003L;
    private Meta meta;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("meta")
    public Meta getMeta ( ) { 
        return this.meta;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("meta")
    public void setMeta (Meta value) { 
        this.meta = value;
    }
 
}
 