/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import org.joda.time.DateTime;

public class ResultShareBuilder {
    //the instance to build
    private ResultShare resultShare;

    /**
     * Default constructor to initialize the instance
     */
    public ResultShareBuilder() {
        resultShare = new ResultShare();
    }

    public ResultShareBuilder shareKey(String shareKey) {
        resultShare.setShareKey(shareKey);
        return this;
    }

    public ResultShareBuilder url(String url) {
        resultShare.setUrl(url);
        return this;
    }

    public ResultShareBuilder shortUrl(String shortUrl) {
        resultShare.setShortUrl(shortUrl);
        return this;
    }

    public ResultShareBuilder size(int size) {
        resultShare.setSize(size);
        return this;
    }

    public ResultShareBuilder dateCreated(DateTime dateCreated) {
        resultShare.setDateCreated(dateCreated);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultShare build() {
        return resultShare;
    }
}