/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultListFolderBuilder 
        extends ResultFolderBuilder {
    //the instance to build
    private ResultListFolder resultListFolder;

    /**
     * Default constructor to initialize the instance
     */
    public ResultListFolderBuilder() {
        resultListFolder = new ResultListFolder();
    }

    public ResultListFolderBuilder meta(Meta meta) {
        resultListFolder.setMeta(meta);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultListFolder build() {
        return resultListFolder;
    }
}