/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class ResultCopyFileBuilder {
    //the instance to build
    private ResultCopyFile resultCopyFile;

    /**
     * Default constructor to initialize the instance
     */
    public ResultCopyFileBuilder() {
        resultCopyFile = new ResultCopyFile();
    }

    public ResultCopyFileBuilder meta(Meta meta) {
        resultCopyFile.setMeta(meta);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultCopyFile build() {
        return resultCopyFile;
    }
}