/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class SessionBuilder {
    //the instance to build
    private Session session;

    /**
     * Default constructor to initialize the instance
     */
    public SessionBuilder() {
        session = new Session();
    }

    public SessionBuilder locale(String locale) {
        session.setLocale(locale);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Session build() {
        return session;
    }
}