/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Storage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5167930267854316937L;
    private String usage;
    private String limit;
    private boolean otl;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usage")
    public String getUsage ( ) { 
        return this.usage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usage")
    public void setUsage (String value) { 
        this.usage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("limit")
    public String getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("limit")
    public void setLimit (String value) { 
        this.limit = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("otl")
    public boolean getOtl ( ) { 
        return this.otl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("otl")
    public void setOtl (boolean value) { 
        this.otl = value;
    }
 
}
 