/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class StorageBuilder {
    //the instance to build
    private Storage storage;

    /**
     * Default constructor to initialize the instance
     */
    public StorageBuilder() {
        storage = new Storage();
    }

    public StorageBuilder usage(String usage) {
        storage.setUsage(usage);
        return this;
    }

    public StorageBuilder limit(String limit) {
        storage.setLimit(limit);
        return this;
    }

    public StorageBuilder otl(boolean otl) {
        storage.setOtl(otl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Storage build() {
        return storage;
    }
}