/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class UploadFileResponseBuilder {
    //the instance to build
    private UploadFileResponse uploadFileResponse;

    /**
     * Default constructor to initialize the instance
     */
    public UploadFileResponseBuilder() {
        uploadFileResponse = new UploadFileResponse();
    }

    public UploadFileResponseBuilder error(String error) {
        uploadFileResponse.setError(error);
        return this;
    }

    public UploadFileResponseBuilder result(ResultUpload result) {
        uploadFileResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UploadFileResponse build() {
        return uploadFileResponse;
    }
}