/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class VersionConflict 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4912702857180692417L;
    private String fail;
    private String ignore;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fail")
    public String getFail ( ) { 
        return this.fail;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fail")
    public void setFail (String value) { 
        this.fail = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ignore")
    public String getIgnore ( ) { 
        return this.ignore;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ignore")
    public void setIgnore (String value) { 
        this.ignore = value;
    }
 
}
 