/*
 * BitcasaLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.cloudfs.models;

import java.util.*;

public class VersionConflictBuilder {
    //the instance to build
    private VersionConflict versionConflict;

    /**
     * Default constructor to initialize the instance
     */
    public VersionConflictBuilder() {
        versionConflict = new VersionConflict();
    }

    public VersionConflictBuilder fail(String fail) {
        versionConflict.setFail(fail);
        return this;
    }

    public VersionConflictBuilder ignore(String ignore) {
        versionConflict.setIgnore(ignore);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public VersionConflict build() {
        return versionConflict;
    }
}